### ISSUE TITLE
Google Drive Sign-In

### ISSUE THREAD

**Issue by SeeenyaOhar** [Senyastr/passpuss#1]
After choosing the import option with Google Drive got this issue.

```
E/flutter ( 3624): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.b: 10: , null, null)
E/flutter ( 3624): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581)
E/flutter ( 3624): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter ( 3624): <asynchronous suspension>
E/flutter ( 3624): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358)
E/flutter ( 3624): <asynchronous suspension>
E/flutter ( 3624):
```

**Comment by SeeenyaOhar** [comment]
The issue has been resolved. No more `com.google.android.gms.common.api.b: 10: ` error.
