### ISSUE TITLE
Switching between Tabs leads to FlutterError

### ISSUE THREAD

**Issue by SeeenyaOhar** [Senyastr/passpuss#3]
Switching from For You tab to Home throws a FlutterException because of disposed DBProvider.

```
Unhandled Exception: A DBProvider was used after being disposed of.
E/flutter (30413): Once you have called dispose() on a DBProvider, it can no longer be used.
E/flutter (30413): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
E/flutter (30413): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
E/flutter (30413): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:234:12)
E/flutter (30413): #3      DBProvider.getPassEntries (package:PassPuss/logic/Database.dart:182:5)
E/flutter (30413): <asynchronous suspension>
E/flutter (30413): #4      HomePageState.assignPairs (package:PassPuss/view/pages/homePage.dart:326:17)
E/flutter (30413): <asynchronous suspension>
E/flutter (30413): 
```

![image](https://user-images.githubusercontent.com/46402350/127978328-cc972d8d-6bc0-45df-bcbe-ab62dae271df.png)

**Comment by SeeenyaOhar** [comment]
The issue has been solved.
